name: Trigger auto deployment for ca-simple-hello

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-simple-hello-AutoDeployTrigger-bb07de41-d644-4ed6-a830-b45eded9bb91.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: crpnacafpeordeveus.azurecr.io
          username: ${{ secrets.CASIMPLEHELLO_REGISTRY_USERNAME }}
          password: ${{ secrets.CASIMPLEHELLO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: crpnacafpeordeveus.azurecr.io/ca-simple-hello:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CASIMPLEHELLO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ca-simple-hello -g PNspoke-rg --server crpnacafpeordeveus.azurecr.io --username  ${{ secrets.CASIMPLEHELLO_REGISTRY_USERNAME }} --password ${{ secrets.CASIMPLEHELLO_REGISTRY_PASSWORD }}
            az containerapp update -n ca-simple-hello -g PNspoke-rg --image crpnacafpeordeveus.azurecr.io/ca-simple-hello:${{ github.sha }}
